import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import GoogleAnalytics from '@/components/GoogleAnalytics';
import CookieBanner from '@/components/cookiebanner';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Serenity',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_MEASUREMENT_ID='G-J6SPCKGY0Y'/>
      <body>
        {children}
      <CookieBanner/>
      </body>
    </html>
  )
}
